Update production-app.yml

diff --git a/.github/workflows/production-app.yml b/.github/workflows/production-app.yml
--- a/.github/workflows/production-app.yml
+++ b/.github/workflows/production-app.yml
@@ -1,40 +1,45 @@
-name: Python application
+name: Python linting and testing
 
 on:
   push:
-    branches: [ main ]
+    branches:
+      - main
   pull_request:
-    branches: [ main ]
-
-permissions:
-  contents: read
+    branches:
+      - main
 
 jobs:
-  build:
-
+  lint-and-test:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-    
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v2
-      with:
-        python-version: "3.10"
-        
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install flake8 pytest pulp
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-        if [ -f environment.yml ]; then conda env update -f environment.yml; fi
-    
-    - name: Lint with flake8
-      run: |
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --max-line-length=127 --max-complexity=10 --statistics --extend-ignore=W291,W293
-        
-    - name: Test with pytest
-      run: |
-        pytest
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install flake8 pytest pulp
+
+      - name: Run flake8
+        run: |
+          # Run flake8 with strict options
+          flake8 . --count --select=E9,F63,F7,F82 --show-source --max-line-length=127 --max-complexity=10 --statistics --extend-ignore=W291,W293
+          
+          # Capture the exit status
+          flake8_status=$?
+
+          # Check if flake8 found any errors
+          if [ $flake8_status != 0 ]; then
+            echo "flake8 found errors. Exiting."
+            exit $flake8_status
+          fi
+
+      - name: Test with pytest
+        run: |
+          pytest
